# Generated by Django 2.2 on 2019-04-10 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('turn', models.IntegerField(choices=[(1, 'Started'), (2, 'Going'), (3, 'Finished')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Player1'), (2, 'Player2')], default=1)),
            ],
            options={
                'verbose_name': 'game',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(default=1, max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='game.Game')),
            ],
            options={
                'verbose_name': 'ship',
            },
        ),
        migrations.CreateModel(
            name='ShipPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('y', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Ship')),
            ],
            options={
                'verbose_name': 'placement',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('x', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('y', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hit', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
            options={
                'verbose_name': 'move',
            },
        ),
    ]
